name: dummmyProject

channels:
  - defaults
  - anaconda
dependencies:
  - python=3.6
  - jupyter
  - pandas
  - scikit-learn
  - tensorflow==1.15
  - pip:
    - mlflow>=1.0
    - papermill
    - bert-serving-client